apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: howest-api
  labels:
    createdBy: "Nathan-Segers"
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: nathansegers/containers_23-24_december_api
          imagePullPolicy: Always
          name: api-demo
          ports:
            - containerPort: 8080
          resources: {}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
         
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30002