services:
  api:
    image: nathansegers/containers_23-24_december_api:versie1
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - 8001:80
  frontend:
    image: nathansegers/containers_23-24_december_frontend:versie1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    environment:
      API_PORT: 80
      API_HOST: api
